<div class="alert alert-block alert-danger" style="color:black"><h2>THIS WORKBOOK IS ASSESSED</h2>
    <p>Each activity details how many marks it is worth (out of 100), and how marks are awarded.</p>
    <p>To make life easier when you submit, we use a two-stage process for each activity:
    <ol>
        <li>We provide a cell where you can edit your code, and which saves your implementation to  file.<br> This is one of the files you will upload to the marking server when you have finished the notebook.</li>
        <li>We then provide a second code cell that loads your implementation into the notebook and tests it.</li>
    </ol> </p>    
    <p>When you are satisfied that you have completed all the activities as required you should:</p>
    <ol>
        <li>Use the jupyterlab functions to download your work (ask your tutor if you need help with this) and save it somewhere sensible so you can find it easily.</li>
        <li>Submit them for automatic marking and feedback by following the links in the <i>Assessments</i> folder on Blackboard.</li>
        <ul>
        <li>This may involve answering some multiple choice questions as well as submitting your code.</li>
        <li><b>Access the feedback provided</b> and use it to improve your work.</li>
        <li>You can have up to <em>four</em> attempts at submitting your work.</li>
    </ol>
<h3> Important instructions about formatting your code cells</h3>
<ol>
   <li>Where you are asked to insert code, or to complete a code skeleton, <b>you must only put code where indicated</b>. <br>
       Otherwise the marking server - or the plagiarism detection we will run later - will not be able to parse and accept them.<br>
       So your code should only go
       <ul> 
           <li><b>After</b> the lines marked <code># ====> insert your code below here </code></li>
           <li> <b>Before</b> the lines marked <code># <==== insert your code above here</code></li>
      </ul>
   </li>
               <li>The marking server will reject any files containing imports except "approvedimports"<br>
               and  it has its own copy of that file, so there is no point editing the one we give you.</li>
<li>Even in comments you must not use any of these banned words: <em>system, read,import</li>
</ol>
</div>

# Workbook 1: Coding practice, introducing numpy and writing your first notebook

Overview of activities and objectives of this workbook:

0. The first part of this workbook will aim to familiarise you with Jupyter notebooks.
    - The two types of cells **code** and **markdown**.
    - Selecting a python environment and running code.
    - The different colour information boxes we use in the workbooks, and what they mean.
<br><br>    
1. The first activity this week is to refresh your python coding skills by writing a simple algorithm that tries all the possible combinations of 4 digits to solve a combination lock puzzle.
    - We provide a simple class for a puzzle with methods to set a problem and test whether an attempt has cracked the code.
    - The task is to implement your algorithm in a method that can be tested using code from the problem class.
<br><br>
2. The second activity asks you to examine your algorithm's performance as the *complexity* of the combination lock changes.
    - For example, we could add more digits, or more values per digit.
    - The task is to use experiments and reasoning to answer a number of interactive multiple-choice questions.
<br><br>

3. The third activity introduces the `numpy` package which is incredibly useful for all sorts of numeric computing.  
   There are some simple code cells to work through which illustrate how to:
    - *Slice* datasets (arrays) to retrieve subsets of their data.
    - Get statistics (e.g. mean/min/max and unique values) of numeric data.
    - Task 3 is to write a method that combines array slicing with some simple string processing to extract a set of values from a character array.
    - For those that feel confident, Task 4 is to combine code snippets from the previous cells to create a new method that could be used as part of a different problem; evaluating an attempt to solve a Sudoku problem.

<div style="background-color:black;width:100%;"><br></div>

# Part 0: Jupyter
If you are seeing this in your browser it means that you have successfully downloaded and run this notebook within your Jupiter environment.

You should have watched the videos that explain how a note book works, and what the different types of cells are.

If you haven't done that, on the module's blackboard go to:

**Learning materials > Getting ready for the module: setting up Jupyter**

- Please take the time to watch the video and run through the simple examples.
- It is important to understand the effect of running and re-running different cells, and the order that you do that.

### Jupyter notebooks contain two types of cells:

**Markdown cells** such as this one, are used to display text and image files on screen. 
- Markdown cells are very useful to keep a record of what you are doing and add notes.
- They can also include html snippets to give you more control over formatting - as the different colour boxes in these notebooks illustrate.

**Code cells** such as the one below, are used to ... run code! Usually python.
- Code cells are like individual python scripts (.py files).
- *But* all variables (data) are shared between all cells in the notebook. So you can create a variable in one cell and it will be accessible in all the other cells as well.

To illustrate this, run the following cell by clicking on it and then pressing **Cmd + Enter** (Mac), or **Ctrl + Enter** (Windows). You should see the variable `x` printed below the cell.

In [1]:
x = 10
print(x)

10


If you run the following cell you should see `x` printed again because it has already been initialised in the cell above.

Now try restarting the notebook, which clears all variables (data):
    - In a browser click **Kernel > Restart Kernel**.
    - In VSCode click **Restart**.

If you run the following cell again you should now see a `NameError` because the variable x hasn't been created yet!   
If you see an error like this, it might be because you haven't run a previous cell where the variable is created *or* the variable simply hasn't been defined anywhere in the notebook.


In [2]:
print(x)

10


### The code for a class or a function has to be put within a single Jupyter cell
It is good practice to separate blocks of code that do different things into separate cells.
And often, you will find yourself wrapping them up as a function or class so you can easily call them from different places.

In Jupyter you must put all the code defining a function, or a class, into one cell.
There are several examples of this below.

- In some cases it means cells may get a little big (e.g. the class for `CombinationProblem`) 
- but once the code has stopped evolving, you can move it out of your notebook into a file (more on this next week)

<div style="background-color:black;width:100%;height:2px"><br></div>

## Colours of markdown boxes

In the notebooks for this module we will use different colours of markdown boxes to communicate different types of information to you.

<div class="alert alert-block alert-info" style="color:black">
<b>Blue</b> boxes are for <b>Activities</b>. This is where we are asking you to <em>do</em> something (usually write code).
</div>

<div class="alert alert-block alert-success" style="color:black">
<b>Green</b> boxes are for <b>Notes</b>, <b>Hints</b> and advice on activities.
</div>

<div class="alert alert-block alert-warning" style="color:black">
<b>Beige</b> boxes are for general <b>Programming</b> or <b>Computer Science</b> related information.
</div>

<div class="alert alert-block alert-danger" style="color:black">
<b>Red</b> boxes are for <b>very important</b> messages, usually to tell you the workbook is assessed.
</div>

## Jupyter python environment

Just like running a normal python (.py) file jupyter notebooks need an python interpreter (environment). Code in this module uses the **AIenv** python environment.

- **IF** you are running the notebooks on the cloud server you need to click on the kernel menu and then change-kernel to **AIenv**.
- **IF** you are running locally AND you created a virtual environment in Jupyter **THEN** click on the kernel menu then change-kernel.
- **OR** in VSCode use the kernel selector in the top-right hand corner.

The **AIenv** environment contains all of the python packages we will use in this module. These need to be imported just like using them in a python file.

**Run the next cell** to import some python packages that we will use in this workbook:
- Section 1 imports some fairly standard python stuff.
   -  It starts with three lines importing functions for  finding, reloading,  and displaying packages within a notebook.
   -  Line 4 imports the `numpy` library. We'll focus more on this at the end of this workbook.
   - The final two lines import some other packages for generating random numbers and finding errors. <br>
- Section 2 tells the python interpreter where to find the folder of common files.
- Section 3 tells python to import one module (file) which contains details of the multiple-choice questions checking your understanding.
 
If you have done the above correctly you should see a series of the success messages printed below the cell when you run it.

Otherwise you might see a `ModuleNotFoundError`:
- First check you have set the kernel to `aienv', then restart the kernel and   rerun the cell
- If that does not work ask your tutor for help.

In [3]:
# section 1: standard python/ jupyter stuff
from sys import path
from importlib import reload
from IPython.display import display,Code
import numpy as np
import random
import traceback
print("Some standard python packages imported")

# section 2: import classes from the common directory for this module
path.append('../common')
print('Path to Module specific classes set')

#section 3: import files specific to this week
import workbook1_mcq1
print("This week's multiple choice questions imported")

print("Everything is imported!")

Some standard python packages imported
Path to Module specific classes set
This week's multiple choice questions imported
Everything is imported!


<div style="background-color:black;width:100%;"><br></div>

# Part 1: Implementing a simple algorithm for a simple problem

We'll start by defining classes for Problem() and CandidateSolution(), so we can rapidly create new types of problems.

The main reason for doing this is so that algorithms know what functions they can call and how.
<img src="figs/simple_uml.png">

### The `CandidateSolution` class represents potential solutions to problems
So an instance of this class represents a single *potential* solution to a problem (so not necessarily *the* solution or even a valid one).

It has 2 variables:
- `variable_values` is a list of variables, whose values represent a solution to a problem  
   like the 4 digits of a combination lock, or a sequence of moves in a game, or ....
- `quality` is an integer which represents if the solution is correct or not (or how good it is).

**Run the cell below to display the contents of this file**

In [4]:
Code(filename='../common/candidatesolution.py', language='python')

"""
Candidatesolution.py
Implements a very simple class
to hold all the variables associated with a candidate solution to a search problem.
Should probably use some private attributes and provide getters and setters
Author: Jim Smith 2023.
"""


class CandidateSolution:
    def __init__(self):
        self.variable_values = []
        self.quality = 0
        self.meets_constraints = False
        self.reason = ""

    def print_values(self):
        print(self.variable_values)

### The `Problem` class is a generic superclass to represent a problem. 
We can create a subclass which defines a specific problem, for example, a combination lock.

It has 2 variables:
- `value_set` is a list of all the valid values that a solution's variables can take.  
    For example,  each digit in a combination should be 0 to 9.
- `numdecisions` is the number of values in a solution e.g. a combination lock often has 4 digits.

And one or two methods:
- The `evaluate()` method takes a `CandidateSolutions` `variable_values` as parameters.  
  It returns a number representing that solution's `quality` e.g. is it correct or not.

**Run the cell below to display the contents of this file**  

In [5]:
Code(filename='../common/problem.py', language='python')

"""Python implementation of superclass for problems
author:james.smith@uwe.ac.uk 2023.
"""


class Problem:
    """Generic super class we will use for problems."""

    def __init__(self):
        self.numdecisions: int = -1
        self.value_set: list = []

    def evaluate(self, solution: list) -> int:
        """Evaluate function.

        Parameters
         ----------
         attempt : list
             list of values that define a proposed solution

         Returns
         -------
         int
             quality
             -1 means invalid,
         Raises
         -----
         ValueError(str)
             reason why solution is invalid
         or
         NotImplementedException
          if the sub class has not implemented an evaluate() method
        """
        raise NotImplementedException("evaluation function has not been defined for problem!")
        return -1,

<div class="alert alert-block alert-warning" style="color:black">
<h3>Generic Coding Skill 1: Using Errors and exceptions to deal with unexpected things at run-time:</h3>
<p> Good programmers think about <b>how</b> the code will be used and <b>what problems</b> might occur.</p>
    <ul>
        <li> For example, we might have a <code>CombinationLock</code> problem where a guess should have 4 digits.</li>
        <li> But what do we do if someone puts in '123' or '54321' or 'abcd'?</li>
        <li> The answer is called <b>Exception Handling</b></li>
        <ul>
            <li> The <em>calling code</em> wraps the call in a try...except block</li>
            <li> And the <em>called</em> code does validation and raises an exception if needed</li>
        </ul>
    </ul>
    <p>In the code below we will use two different types of errors you will come across a lot:
    <ul> 
        <li><code>NotImplementedError</code>: when a sub-class fails to implement a method, and so the abstract class method is called by accident.</li>
        <li><code>ValueError</code>: when a problem's <code>evaluate()</code> method is asked to test something that doesn't make sense.</li>
        <li> We will let the <code>NotImplementedError</code> stop our programme executing, because it means something needs fixing.</li>
        <li> But the search method uses a <code>try ....except</code> block around each attempt to evaluate a solution so that it can carry on after producing something invalid.</li>
    <ul>
    </p>
</div>

<div class="alert alert-block alert-warning" style="color:black">
<h3>Generic Coding Skills 2: Taking Care to format doc strings for each method</h3>
   Can seem like a lot of extra effort but:
    <ul> 
        <li>Makes it easier for other people to use your code (like we are doing with you).</li>
        <li>Makes it easier for you to  come back to code you wrote a few months ago.</li>
        <li>Can be understood by IDEs and  automatic code documenters.</li>
    </ul>
    <p> We've used strict PEP8 naming conventions, docstrings and type hints for parameters to methods. <br>
        This is good coding practice and many github repositories will use automated checks to enforce them.</p>
</div>

### The `CombinationProblem` subclass defines combination lock problems
<a title="Immanuel goldstein at English Wikipedia, Public domain, via Wikimedia Commons" href="https://commons.wikimedia.org/wiki/File:CombinationBikeLock.JPG"><img width="256" style="float:right" alt="CombinationBikeLock" src="https://upload.wikimedia.org/wikipedia/commons/b/b7/CombinationBikeLock.JPG"></a>

The lock has a number of **tumblers** or **digits** (4 in the picture, more expensive locks have more).

There are the same number of options for each tumbler, typically (but not always) 10, the digits 0 to 9.

When the lock is made, each of the tumblers is set with it's own specific value.

So in code: an attempt to open the lock means testing whether each of variables has got the right value.


An **instance** of `CombinationProblem`  represents a specific combination lock.

This class has 3 variables:
- `numdecisions` is the number of tumblers or digits in the lock.
- `value_set` is the list of values each tumbler can have: \[0,1,2,3,4,5,6,7,8,9\]
- `goal` is the solution or combination to open the lock. When we create a new instance of this problem the goal is set to a random combination.

The `Evaluate()` method:
1. Checks if a given solution is the right length (e.g. 4 digits)
2. Checks if the each digit is a valid value (e.g. an integer in the range 0 to 9)
3. Checks if the solution is correct. If so, return 1 otherwise 0.

The `get_goal()` and `set_goal()` methods: provide clean ways to access an instance's goal values

**Run the cell below to display the code that implements this class**

In [6]:
Code(filename='../common/combinationproblem.py', language='python')

import random
from problem import Problem

class CombinationProblem(Problem):
    """
    Class to create simple combination lock problems
    and report whether a guess opens the lock
    """

    def __init__(self, tumblers: int = 4, num_options: int = 10):
        """Create a new instance with a random solution
        Parameters
        ----------
        tumblers:int
           number of tumblers
           default 4
        num_options:int
           number of possible values (positions) for each tumbler
           this version assumes they are a consecutive integers from 1 to num_options
           default 10
        """

        self.numdecisions = tumblers  # number of tumblers
        # set the allowed values in each position
        self.value_set = []
        for val in range(1, num_options + 1):
            self.value_set.append(val)

        # set  new random goal (unlock code)
        self.goal = []
        for position in range(tumblers):
            new_random_val = random.choice(self.value_set)
            self.goal.append(new_random_val)

    def get_goal(self) -> list:
        """helper function -prints  target combinbation to screen"""
        return self.goal
    
    def set_goal(self,newgoal:list):
        if len(newgoal) != self.numdecisions:
            raise ValueError('newgoal has the wrong length')
        else:
            for pos,val in enumerate(newgoal):
                self.goal[pos]=val

    def evaluate(self, attempt: list) -> int:
        """
        Tests whether a provided attempt matches the combination
        Parameters
        ----------
        attempt: list
            list of values that define a proposed solution
        Returns
        ---------
        int
            quality
            -1 means  attempt is invalid, (e.g. too few or wrong values)
            0 means valid but incorrect,
            1 means correct
        Raises
        ------
        ValueError with reason why solution is invalid
        """
        #  how long is the solution?
        N = len(attempt)
        if N is not self.numdecisions:
            raise ValueError( "Error:attempt is wrong length")

        # is the solution made up of valid choices?
        for pos in range(N):
            if attempt[pos] not in self.value_set:
                raise ValueError( "Error: invalid value found in solution")

        # have we found the right combination?
        if attempt == self.goal:
            return 1
        else:
            return 0
        
        
    def display(self, guess: list):
        """Displays a guess at the combination
        simple print as guess does not need any decoding.

        Parameters
        ----------
        attempt : candidateSolution
            object whose variable values are to be displayed
        """
        print(guess)

The next two code cell shows you how to use these classes and test a solution - including tests for unsuitable inputs.  
**Run the two cells below to import and then use the classes**
- the first cell makes your python interpreter  aware of (import) the classes. It should not produce an output.
- the second cell  uses the classes. It should produce some outputs.  
  Make sure you understand why some lines get printed and some don't.

In [7]:
from candidatesolution import CandidateSolution
from problem import Problem
from combinationproblem import CombinationProblem

In [8]:
# Create a new lock problem 
my_lock = CombinationProblem(tumblers=4, num_options=10)
print(f'Made new combination lock with goal {my_lock.get_goal()}')
# Create an empty candidate solution
my_attempt = CandidateSolution()

# Create a variable to hold the result
result = "no score returned"

# Try some guesses
# First two are not valid and the last one is correct
my_guesses= [
    [1,2,3],
    [1,2,3,'a'],
    [1,2,3,4]
]

for guess in my_guesses:
    try:
        print(f'Trying guess {guess}:')

        # Create a guess by setting the variable values in the candidate solution
        my_attempt.variable_values = guess

        # Evaluate the guess by calling the evaluate method of the lock
        result = my_lock.evaluate(my_attempt.variable_values)

    except ValueError as e:
        print(e)
    print(f'Score was: {result}\n')

Made new combination lock with goal [4, 6, 8, 10]
Trying guess [1, 2, 3]:
Error:attempt is wrong length
Score was: no score returned

Trying guess [1, 2, 3, 'a']:
Error: invalid value found in solution
Score was: no score returned

Trying guess [1, 2, 3, 4]:
Score was: 0



<div class="alert alert-block alert-info" style="color:black"><h2>Activity 1: Implement a simple brute-force algorithm to solve a combination lock puzzle</h2>
    <h3><b>40 marks</b> for correct implementation that passes a copy of the test below on the marking server</h3>
    To complete this activity you need to implement the `exhaustive_search_4tumblers` method in the cell below.<br>
    <ul>
    <li>The puzzle will have 4 digits so you can hard-code the number of loops.</li>
    <li><b>Don't over-think this</b>: my 'reference version' only adds ~10 lines of code to the skeleton code.</li>
    <li>Before submitting run the second code cell below to test your algorithm.</li>
    <li><b>DO NOT PUT ANY CODE OUTSIDE THE PLACES INDICATED.</b></li>
    <br><b>How to get started:</b> Your code should:
    <ol>
        <li> Take as a parameter a new puzzle instance with 4 tumblers.</li>
        <li> One-by-one, for every possible combination:
            <ul> 
                <li> Write the new combination into <code>my_attempt.variable_values</code></li>
                <li> Test if that is the correct solution by calling<br> 
                    <code>result=puzzle.evaluate(my_attempt.variable_values)</code> and using <code>try...except</code> exception handling</li>
                <li>Stop and return the correct answer as soon as you have found the right solution (result=1)</li>
            </ul>
        </li>
    </ol>
</div>

<div class="alert alert-block alert-success" style="color:black"><b>Hints:</b> 
    <ul>
        <li>It's easiest to do this with four nested for loops (but other methods might be easier to adapt to different situations).</li>
        <li>Each loop runs over all the possible values a tumbler can have.</li>
        <li> It makes your code more reusable if you do this using <code>for loop_var in (puzzle.value_set)</code> where you use a different variable name for each loop.</li>   
        <li>If your 4 loop variables are called digit1, digit2, digit3, digit4 then you can set <code>attempt.variable_values = [digit1, digit2, digit3, digit4]</code></li>
        <li>Remember to wrap any calls to evaluate() in a try except block as illustrated in the cell below.</li>
    </ul>
</div>

<div class="alert alert-block alert-danger" style="color:black">
    Remember this is a two-stage process: <ol>
        <li>Edit then run the first  cell to save your implementation to  file.<br> This is one of the files you will upload to the marking server when you have finished the notebook.</li>
        <li>Run the second cell to load your implementation into the notebook and test it.</li>
    </ol> </div>

**Write your code where indicated in the cell below, then run it to save your code to file**

In [9]:
%%writefile  'studentcode/student_wb1.py'
from approvedimports import *

def exhaustive_search_4tumblers(puzzle: CombinationProblem) -> list:
    """simple brute-force search method that tries every combination until
    it finds the answer to a 4-digit combination lock puzzle.
    """

    # check that the lock has the expected number of digits
    assert puzzle.numdecisions == 4, "this code only works for 4 digits"

    # create an empty candidate solution
    my_attempt = CandidateSolution()
    
    # ====> insert your code below here
    my_attempt.variable_values = []
    for i in puzzle.value_set:
        for j in puzzle.value_set:
            for k in puzzle.value_set:
                for l in puzzle.value_set:
                    my_attempt.variable_values = [i, j, k, l]
                    try:
                        result = puzzle.evaluate(my_attempt.variable_values)
                        if result:                        
                            return my_attempt.variable_values
                    except ValueError as e:
                        print(e)

    # <==== insert your code above here
    
    # should never get here
    return [-1, -1, -1, -1]

Overwriting studentcode/student_wb1.py


**Run the code cell below to load and test your code.** It should output messages and feedback.

There are three parts:
1. Importing the function you wrote
2. A function that gets called (with lots of try_excepts to report on bugs).
3. Running a set of test cases using your code: 
    - one random valid one
    - and some to catch "edge-cases" e.g. there are loops that might not be quite right


In [10]:
#1: Load your code
if 'studentcode' not in path:
    path.append('studentcode')
import student_wb1 as student 
reload (student)

# 2: the test function
def test_exhaustive_search_4tumblers(target:list):
    """function to test implementation of exhaustive search"""

    # create new puzzle
    puzzle = CombinationProblem(tumblers=4, num_options=10)

    # option to over-ride the random target 
    if len(target)==4:
        puzzle.set_goal(target)

    # call function to solve the puzzle
    # wrap it in a try...except to help debug incorrect code
    try:
        print(f'\tlooking for goal {puzzle.get_goal()}')
        search_answer = student.exhaustive_search_4tumblers(puzzle)

        if search_answer == puzzle.goal:
            message = "Well done"
        else:
            message = (f"Something went wrong: your code returned the answer {search_answer}")
            message += f" but the real answer was {puzzle.goal}"

    except Exception as e:
        message = "Something went wrong with your code.\n"
        message += "Here is the stack trace which should let you find the error\n"
        message += traceback.format_exc()

    # assertion fails and prints the message if something went wrong
    assert message == "Well done", message
    print(f"\tyour code correctly found the solution {puzzle.goal}")



#3 Test your code
#  Call the function for random target test case
print('Testing with a random target code:')
test_exhaustive_search_4tumblers(target=[])

# Call the function to test the edge cases
nextpuzzle = CombinationProblem()
allowed = nextpuzzle.value_set

print(f'\nNow testing that your code uses the right set of possible values: {allowed}')
for value in allowed:
    mytarget = [value, value, value, value]
    test_exhaustive_search_4tumblers(target=mytarget)

Testing with a random target code:
	looking for goal [10, 6, 8, 9]
	your code correctly found the solution [10, 6, 8, 9]

Now testing that your code uses the right set of possible values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
	looking for goal [1, 1, 1, 1]
	your code correctly found the solution [1, 1, 1, 1]
	looking for goal [2, 2, 2, 2]
	your code correctly found the solution [2, 2, 2, 2]
	looking for goal [3, 3, 3, 3]
	your code correctly found the solution [3, 3, 3, 3]
	looking for goal [4, 4, 4, 4]
	your code correctly found the solution [4, 4, 4, 4]
	looking for goal [5, 5, 5, 5]
	your code correctly found the solution [5, 5, 5, 5]
	looking for goal [6, 6, 6, 6]
	your code correctly found the solution [6, 6, 6, 6]
	looking for goal [7, 7, 7, 7]
	your code correctly found the solution [7, 7, 7, 7]
	looking for goal [8, 8, 8, 8]
	your code correctly found the solution [8, 8, 8, 8]
	looking for goal [9, 9, 9, 9]
	your code correctly found the solution [9, 9, 9, 9]
	looking for goal [10, 1

<div style="background-color:black;width:100%;"><br></div>

# Part 2: Analysing your algorithm's behaviour as the complexity of the problem grows

<div class="alert alert-block alert-info" style="color:black"><h2>Activity 2: Analysing your algorithm's effectiveness and efficiency</h2>
    <h3><b>40 marks</b> - 5 marks each for the first six questions, 10 for the seventh</h3>
     <ol>
         <li> Run the next cell and answer the multiple-choice questions to check your understanding of your algorithm.</li>
         <li> You will be asked similar questions when you submit your work for  automated marking.</li>
    </ol>
    <br><b>How to get started:</b>
    Use a combination of learning skills to find out answers to the questions below:
    <ol> 
        <li><b>active learning</b> : experiments,</li> 
        <li><b>theory learning</b> : your understanding based on reasoning,</li>
        <li><b>reflective learning</b> : thinking about why answers might have been wrong,</li>
        <li><b>pragmatic learning</b> : trial-and-error</li>
    </ol>
</div>

<div class="alert alert-block alert-success" style="color:black"><b>Hints:</b>
    <ul>
        <li>It's often a good idea to check your understanding of how the method works <b> in theory</b> against <b>observations</b></li> 
        <li>So to check some of your answers you might want to add some print statements to your code.</li>
        <li>Remember that the marking server wants to see your method working for 4 tumblers. So if you want to experiment with what happens if there are more or less tumblers, you'll need to add a new cell to the notebook and  make a copy of your function with a different name.</li>
</div>

In [ ]:
print(
    "\nThese first three questions check how your algorithm should run with the settings provided.\n"
)
display(workbook1_mcq1.Q1)
display(workbook1_mcq1.Q2)
display(workbook1_mcq1.Q3)

print(
    "\n The next questions ask you to think about how fast the search space grows as you change the puzzle definition.\n"
)

display(workbook1_mcq1.Q4)
display(workbook1_mcq1.Q5)
display(workbook1_mcq1.Q6)
display(workbook1_mcq1.Q7)


These first three questions check how your algorithm should run with the settings provided.




 The next questions ask you to think about how fast the search space grows as you change the puzzle definition.



<div style="background-color:black;width:100%;"><br></div>

# Part 3: Introducing the numpy package for storing and manipulating numerical data
<img src="figs/slicing.png" alt="Image of a rectangular grid with colours indicating how rows, columns and blocks of cells can be selected."  style="float:right" size:300/>

Python has a **numpy** module with lots of useful code for doing math, and creating and manipulating arrays of data. 

There are **lots** of books and online resources to help you learn about numpy. Good websites include [W3schools](https://www.w3schools.com/python/numpy/default.asp) and [geeksforgeeks](https://www.geeksforgeeks.org/python-numpy/). Of course you can ask specific questions if you're stuck with bits of coding on [stackoverflow](https://stackoverflow.com/questions/tagged/python).

### Finding the size of arrays
- numpy arrays are created using ```np.array()```
- numpy arrays can be:
  - 1 dimensional (like a vector)
  - N-dimension (like a matrix or a table)
- All numpy arrays have a ```.shape``` attribute
   - either a scalar (integer) value giving the length of a 1D array
   - or a list of values holding the size of different dimensions
   - for the 2-dimensional array `X` in the image ```X.shape= [7,5]```, because it has 7 rows and 5 columns

### Slicing arrays
If we have a 2D numpy array `X`  we can select just parts of it - i.e. groups of rows, or columns, by "slicing".

We specify the range of rows we want, then the range of columns using ```X[start_row: end_row, start_col: end_col]```
- For each dimension, the start and end index are separated by a colon (:).
- The dimensions (row, columns, etc) are separated by a comma (,).
- The end_row and end_col are not included in the slice.
- If start is empty, then the slice goes right from the start of that dimension (row/column)
- If end is empty, then the slices goes right to the end of the dimension (row/column)
- if both are empty (or missing), then the whole of that dimension is included
- If the start is empty and the end is negative, the slices comes from the end of the row/column.

The image shows how these rules allow different ways of specifying the same slice. 

**Example 1:** If we put the letters of my name into a 1D array then we can pick out what we want.

**Run the cell below:** make sure you understand how the output is produced.

In [12]:


# Example 1
print("Declaring a 1D array:")
jims_name = np.array(["j", "i", "m", " ", "s", "m", "i", "t", "h"])

print(f"the variable jims_name is of type {type(jims_name)}")
print(f"it  has value {jims_name}\nand  shape {jims_name.shape} and {len(jims_name.shape)} dimension.\n")

# Use slicing to get only first name
print("Extracting a range of values from a 1D array e.g. jims_name[0:3]:")
print(jims_name[0:3])

Declaring a 1D array:
the variable jims_name is of type <class 'numpy.ndarray'>
it  has value ['j' 'i' 'm' ' ' 's' 'm' 'i' 't' 'h']
and  shape (9,) and 1 dimension.

Extracting a range of values from a 1D array e.g. jims_name[0:3]:
['j' 'i' 'm']


**Example 2:** If we have all the tutors names we could pick out just one row, or the n-th letter in all their names.

Notice how numpy lets us specify  contents  using python's list syntax. 
So for 2 dimension we can use a *list of lists*

**Run the two cells below.** The first one creates the array, the second one illsutrates some slicing operations.


In [13]:
# Example 2- creating a 2d array
print("\n Declaring a 2D array:")
tutors_names = np.array(
    [
        ['J', 'i', 'm', ' ', ' ', ' ', ' ', 'S', 'm', 'i', 't', 'h', ' '],
        ['N', 'a', 't', 'h', 'a', 'n', ' ', 'D', 'u', 'r', 'a', 'n', ' '],
        ['A', 'i', 'n', 'a', ' ', ' ', ' ', 'M', 'a', 's', 't', 'o', 'i']
    ],
    dtype=str,
)
print(f"{tutors_names}")

print(
    f"\nThe variable tutors_names has shape {tutors_names.shape}\n"
    f" - so if we print tutors_names.shape[0] we see it has {tutors_names.shape[0]} rows\n"
    f" - and if we print tutors_names.shape[1] we see it has {tutors_names.shape[1]} columns"
)


 Declaring a 2D array:
[['J' 'i' 'm' ' ' ' ' ' ' ' ' 'S' 'm' 'i' 't' 'h' ' ']
 ['N' 'a' 't' 'h' 'a' 'n' ' ' 'D' 'u' 'r' 'a' 'n' ' ']
 ['A' 'i' 'n' 'a' ' ' ' ' ' ' 'M' 'a' 's' 't' 'o' 'i']]

The variable tutors_names has shape (3, 13)
 - so if we print tutors_names.shape[0] we see it has 3 rows
 - and if we print tutors_names.shape[1] we see it has 13 columns


In [14]:
#Example 2 - extracting information from the  2d array

print("Extracting a row with all its columns from a 2D array, e.g. tutors_names[1, :] ")
print(tutors_names[1, :])  # every column of the second row

print("\nExtracting a range of columns from every row of a 2D array e.g., tutors_names[:, 0:6]")
print(tutors_names[:, 0:6])

# This example uses negative index to select  from the end of a slice
print("\nExtracting a specific block of data from a 2D array e.g. tutors_names[2, -6]")
print(tutors_names[2, -6:])
print(
    " - note how this example used negative indexing to count from the end not the start"
)

Extracting a row with all its columns from a 2D array, e.g. tutors_names[1, :] 
['N' 'a' 't' 'h' 'a' 'n' ' ' 'D' 'u' 'r' 'a' 'n' ' ']

Extracting a range of columns from every row of a 2D array e.g., tutors_names[:, 0:6]
[['J' 'i' 'm' ' ' ' ' ' ']
 ['N' 'a' 't' 'h' 'a' 'n']
 ['A' 'i' 'n' 'a' ' ' ' ']]

Extracting a specific block of data from a 2D array e.g. tutors_names[2, -6]
['M' 'a' 's' 't' 'o' 'i']
 - note how this example used negative indexing to count from the end not the start


<div class="alert alert-block alert-info" style="color:black"><h2>Activity 3: Practising numpy slicing</h2>
    <h3><b>10 marks</b> for an implementation that passes the test</h3>
    Making use of the snippets above, write a function <code>get_names(namearray:np.ndarray)->list</code> that:
    <ol>
        <li>Takes the array <code>tutors_names</code> as a parameter</li>
        <li>Creates smaller array containing just the family names <br>
        <b> Assume the family names are all held in the last six characters</b>
        <li>Uses the python <code>str.join method</code> to turn each family name into a single string</li>
        <li>Appends all the names to a list</li>
        <li>Returns that list containing the family names </li>
    </ol>
    <b>Note:</b> that the marking server will use a different array of names. Your code should work if we test it with different arrays (as long as the family names have the same maximum length).
    <br><br><b>How to get started:</b> Like all coding (especially if the coder is something like chat-gpt), it's always a good idea to start by asking how you would test your code.
    <ul>
        <li>In this case I've given you a test function to help you make sure you've understood the requirements.</li>
        <li><b>Most answers from chat-gpt or stackoverflow are likely to be wrong</b><br>
            because they will probably break up <code>namearray</code> into  strings they split up using spaces.<br>
            In this task you are asked to demonstrate <b><emp>slicing</emp></b> based on <b><emp>position</emp></b>.</li>
    </ul>
</div>

 <div class="alert alert-block alert-success" style="color:black"><b>Hints:</b>
    <ol>
        <li><b>Nothing in your code should reference the array <code>tutors_names</code></b>.<br>
            That was just an example, your code should be generic.<br>
            The function is passed an array <code>namearray</code> - you should access and extract names from this.</li>
        <li>Try the answers in <a href="https://stackoverflow.com/questions/12453580/how-to-concatenate-join-items-in-a-list-to-a-single-string">this question</a> to see how to make strings out of the characters in a name.</li>
        <li>My solution has one <code>for</code> loop (using <code>namearray.shape[0]</code> to access the number of rows) and 3 lines of code inside the loop.</li>
        <li>If you look at the original array you'll see I've put spaces after my and Nathan's family names</li>
        <li>Use the cell below to develop your code and the one after to test it.</li>
    </ol>
</div>

**Write your code where indicated in the cell below then run it to save your code to file**

In [15]:
%%writefile -a "studentcode/student_wb1.py"

def get_names(namearray: np.ndarray) -> list:
    family_names = []
    # ====> insert your code below here
    for i in range(namearray.shape[0]):
        family_name_arr = namearray[i, -6:]
        family_name_str = ''
        family_name_str = family_name_str.join(family_name_arr)
        family_names.append(family_name_str)
    
    # <==== insert your code above here
    return family_names

Appending to studentcode/student_wb1.py


**Run the cell below to load and test your code**

A different array will be used when your code is marked

In [16]:
# Step 1: load your code
if 'studentcode' not in path:
    path.append('studentcode')
import student_wb1 as student
reload (student)


# Step 2: define test function
def test_get_names():
    """An example of writing a test using an assertion to check code does what it should,
    and creating error string to give more information.
    NOTE: we will test your code using different arrays, so you can't hard-code the answers!
    """

    # Declare the array to be used in the test
    tutors_names2 = np.array(
        [
            ["J", "i", "m", " ", " ", " ", " ", "S", "m", "i", "t", "h", " "],
            ["N", "a", "t", "h", "a", "n", " ", "D", "u", "r", "a", "n", " "],
            ['A', 'i', 'n', 'a', ' ', ' ', ' ', 'M', 'a', 's', 't', 'o', 'i'],
        ],
        dtype=str,
    )
 
    # Call the function
    returned_value = student.get_names(tutors_names2)

    # Check the result
    correct_value = ["Smith ", "Duran ", "Mastoi"]
    # make error msg
    error_msg = f"returned value {returned_value} should be {correct_value}"
    # this is the test, error_msg is printed if it fails
    assert returned_value == correct_value, error_msg
    print("passed all tests")

#step 3: Run the test function on your code
test_get_names()

passed all tests


<div style="background-color:black;width:100%;height:2px"><br></div>

### Useful numpy functions

The real benefits of numpy arrays come when they hold numerical data.

Numpy provides **lots** of built-in mathematical functions, here we'll just illustrate a few that you'll use in this course

### Making arrays full of zeros/ones etc
- via functions like ```np.zeros((rows, columns), datatype)```
- see [the numpy documentation](https://numpy.org/doc/stable/reference/routines.array-creation.html) for more details

### Statistics that describe contents: mean, max and min
- if we call ```np.mean(my_1D_array)```,  ```np.max(my_1D_array)``` or ```np.min(my_1D_array)``` on a 1D array we get what you would expect
- if we call the methods on a N-Dimensional array we get results for the whole array
- but we can also get it for different dimensions by specifying what *axis* we want
- and ```np.argmax(myarray)``` or ```np.argmin(myarray)``` tell us *where* the biggest/smallest values are in the array

### Functions that manipulate arrays into different shapes
- `np.reshape()` can be suprisingly handy, especially for getting data into the right format for a machine learning algorithm 

**Work through the 5 cells below, reading then running them:**  
make sure you understand what they are doing - you'll be using these functions a lot in the next few weeks. 
- The first cell makes an array, fills it with consecutive numbers, then shuffles them into a random order

In [17]:
# make a 1d array of 100 zeros (as integers)
my_1darray = np.zeros(100, dtype=int)

# fill it with consecutive values starting from 1 - this code doesn't care how big the array is
for position in range(my_1darray.shape[0]):
    my_1darray[position] = position + 1
print(f"The 1D-version of the array looks like this:\n{my_1darray}\n")

# let's shuffle the array first
np.random.shuffle(my_1darray)
print(f"The shuffled version of the array looks like this:\n{my_1darray}\n")

# now we can just 'reshape' this long array into a square
my_2darray = my_1darray.reshape(10, 10)
print(f"The 2D-version looks like this:\n{my_2darray}")

The 1D-version of the array looks like this:
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]

The shuffled version of the array looks like this:
[ 30  77  50  94  74  34  11  91  79  60  95  38  32  46  23  92  39  25
  29  55   9   2  87  68  72  48  18  35  75  17  14  26  65  27  45  58
  12  57  81  67  54  10  40  66  21  20  96  33  63  83  99  64  47  85
  44  78  19  53 100  22  24  52  89  15  98  76  16  86  28  93  56  61
  49  31  42  70   1  82  69  73  97  41   4  37  88   6  59   8  84  71
  43   5  62  80  51   7  90   3  36  13]

The 2D-version looks like this:
[[ 30  77  50  94  74  34  11  91  79  60]
 [ 95  38  32

- the next cell finds all unique values in an array  and (optionally) how many of each

In [18]:
# getting the unique values in an array
uniques = np.unique(my_1darray)
print(f"np.unique returns an array of the different values present which are:\n{uniques}\n")

print(f"we can use the shape attribute to see there are there are {uniques.shape[0]} different values in the array")

np.unique returns an array of the different values present which are:
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]

we can use the shape attribute to see there are there are 100 different values in the array


- Now lets find some statistics

In [19]:
# 1D means and max
oneD_biggest = np.max(my_1darray)
oneD_mean = np.mean(my_1darray)
print(f" the one-D array has biggest value {oneD_biggest} and mean {oneD_mean}")

 the one-D array has biggest value 100 and mean 50.5


In [20]:
# 2d versions
twoD_biggest = np.max(my_2darray)
twoD_mean = np.mean(my_2darray)
print(f"The two-D array also has biggest value {twoD_biggest} and mean {twoD_mean}\n")

print("But we can also get row/column stats by asking the numpy max/mean/min functions to report by axes\n"
      "in which case they return a list: one value per row/column")
row_wise_biggest = np.max(my_2darray, axis=0)
row_wise_mean = np.mean(my_2darray, axis=0)
column_wise_biggest = np.max(my_2darray, axis=1)
column_wise_mean = np.mean(my_2darray, axis=1)

print(f"- row-by-row maxima are {row_wise_biggest}")
print(f"- column-by-column means are {column_wise_mean}")

The two-D array also has biggest value 100 and mean 50.5

But we can also get row/column stats by asking the numpy max/mean/min functions to report by axes
in which case they return a list: one value per row/column
- row-by-row maxima are [ 99  77  89  94  98  92  96  91 100  93]
- column-by-column means are [60.  47.4 43.1 45.2 48.6 61.1 57.7 53.4 49.5 39. ]


In [21]:
# locations of max in 1D array- we already found the max value toe cells above this
location = np.argmax(my_1darray)
print(f"The biggest value is {oneD_biggest} found in location {location}")

The biggest value is 100 found in location 58


<div class="alert alert-block alert-info" style="color:black"><h2>Activity 4: Checking Sudoku</h2>
    <h3><b>10 marks</b> for an implementation that passes the test</h3>
    Making use of the snippets above, write a function <code>check_sudoku_array(attempt: np.ndarray) -> int</code> that:
    <ol>
        <li>Takes a 2d numpy array <code>attempt</code> as input</li>
        <li>Uses assertions to check that the array has 9 rows and 9 columns</li>
        <li>Define 27 <em>slices</em> or sub-arrays corresponding to the 9 sub-squares, 9 rows and 9 columns</li>
        <li>Returns an integer saying how many of the 27 slices contain exactly 9 unique values</li>
    </ol>
    <b>Note:</b> this is a <em>Stretch</em> activity so don't worry if you can't complete it easily.
    <br><br><b>How to get started:</b>
    <ul>
        <li>We've given you some pseudocode in comments and declared some variables to get you started.</li>
        <li>You will need to define 27 numpy arrays to hold the  different slices. Here are three of them to get you started:<br>
            <code>row1 = attempt[1,:]</code> (you will need to get all the rows).<br>
            <code>col9 = attempt[,:8]</code> (you will need to get all the columns).<br>
            <code>top_middle_square = attempt[0:3, 3:6]</code> (you will need to get all the sub-squares).</li>
        <li>Store these slices in a list by appending them to the list called <code>slices</code>.</li>
        <li>Use <code>np.unique(slices)</code> to check that each slice has 9 unique values.</li>
        <li>Return an integer saying how many of the 27 checks the attempt passes.</li>
    </ul>
</div>

<div class="alert alert-block alert-success" style="color:black"><b>Hints:</b>
    <ul>
        <li>All the code you need is available above - it is a matter of assembling the bits correctly.</li>
        <li>If you don't want to define each slice by hand, (like I have started doing above), you could do it <em>programmatically</em>
        <ul>
            <li>by iterating over (0...8) you can define (and then add to the list) the slices for the rows and columns automatically</li>
            <li>and then add the 9 sub-square slices either by hand or using 2 nested loops. One dealing with moving the box across the grid, another dealing with moving it up and down</li>
        </ul>
    </ul>
</div>

**Write your code where indicated in the cell below then run it to save your implementation to file**

In [26]:
%%writefile -a "studentcode/student_wb1.py"

def check_sudoku_array(attempt: np.ndarray) -> int:
    tests_passed = 0
    slices = []  # this will be a list of numpy arrays
    
    # ====> insert your code below here


    # use assertions to check that the array has 2 dimensions each of size 9
    arr_dim = (9, 9)
    assert attempt.shape == arr_dim, 'Incorrect array'

    ## Remember all the examples of indexing above
    ## and use the append() method to add something to a list
    for i in range(arr_dim[0]):
        slices.append(attempt[i, : ])
    for i in range(arr_dim[1]):
        slices.append(attempt[ : , i])
    for i in range(0, arr_dim[0], 3):
        for j in range(0, arr_dim[1], 3):
            slices.append(attempt[i:i+3, j:j+3])

    unique_values_no = 0
    for slice in slices:  # easiest way to iterate over list
        # print(slice) - useful for debugging?
        print(slice)
        # get number of unique values in slice
        unique_values_no = np.unique(slice).shape[0]
        # increment value of tests_passed as appropriate
        tests_passed += 1 if unique_values_no == 9 else 0
    print(tests_passed)
    
    # <==== insert your code above here
    # return count of tests passed
    return tests_passed

Appending to studentcode/student_wb1.py


**Run the cell below to load and test your code**

In [27]:
# Step 1: load your code
if 'studentcode' not in path:
    path.append('studentcode')
import student_wb1 as student
reload (student)

#Step 2: define a possible solution to test
attempt = np.array(
    [
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [2, 3, 4, 5, 6, 7, 8, 9, 1],
        [3, 4, 5, 6, 7, 8, 9, 1, 2],
        [4, 5, 6, 7, 8, 9, 1, 2, 3],
        [5, 6, 7, 8, 9, 1, 2, 3, 4],
        [6, 7, 8, 9, 1, 2, 3, 4, 5],
        [7, 8, 9, 1, 2, 3, 4, 5, 6],
        [8, 9, 1, 2, 3, 4, 5, 6, 7],
        [9, 1, 2, 3, 4, 5, 6, 7, 8],
    ]
)
# Step 3 test your code for this candidate solution
passed = student.check_sudoku_array(attempt)
assert passed==18,( "Error, the rows and columns are all unique "
                   "but not the inner squares, score should be 18")
print('your code correctly identified that 18 of 27 the constraints are met')

[1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9 1]
[3 4 5 6 7 8 9 1 2]
[4 5 6 7 8 9 1 2 3]
[5 6 7 8 9 1 2 3 4]
[6 7 8 9 1 2 3 4 5]
[7 8 9 1 2 3 4 5 6]
[8 9 1 2 3 4 5 6 7]
[9 1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9 1]
[3 4 5 6 7 8 9 1 2]
[4 5 6 7 8 9 1 2 3]
[5 6 7 8 9 1 2 3 4]
[6 7 8 9 1 2 3 4 5]
[7 8 9 1 2 3 4 5 6]
[8 9 1 2 3 4 5 6 7]
[9 1 2 3 4 5 6 7 8]
[[1 2 3]
 [2 3 4]
 [3 4 5]]
[[4 5 6]
 [5 6 7]
 [6 7 8]]
[[7 8 9]
 [8 9 1]
 [9 1 2]]
[[4 5 6]
 [5 6 7]
 [6 7 8]]
[[7 8 9]
 [8 9 1]
 [9 1 2]]
[[1 2 3]
 [2 3 4]
 [3 4 5]]
[[7 8 9]
 [8 9 1]
 [9 1 2]]
[[1 2 3]
 [2 3 4]
 [3 4 5]]
[[4 5 6]
 [5 6 7]
 [6 7 8]]
18
your code correctly identified that 18 of 27 the constraints are met


<div class="alert alert-block alert-success" style="color:black"><b>Save and close Jupyter:</b>
    <ol>
        <li>Use the jupyterlab functions to download your work (ask your tutor if you need help with this) and save it somewhere sensible so you can find it easily.</li>
        <li>Shutdown the notebook when you have finished with this tutorial (menu->file->close and shutdown notebook)</li>
    </ol>
</div>